name: MiniGames
main: com.mcmiddleearth.minigames.MiniGamesPlugin
version: 1.0
description: MiniGames plugin
load: POSTWORLD
softdepend: [Multiverse-Core]
commands:
    game:
        description: manage MiniGames plugin
        usage: TBA
    gc:
        description: MiniGames chat message
        usage: /gc <message> Sends a message to all participants of the MiniGame
permissions:
    minigames.*:
        description: Gives access to all miniGames commands
        default: op
        children:
            minigames.staff: true
    minigames.staff:
        description: Gives access to /game delete command
        default: op
        children:
            minigames.manager: true
    minigames.manager:
        description: Gives guides access to minigames commands for managing games
        default: op
        children:
            minigames.user: true
    minigames.user:
        description: Gives access miniGames commands for players
        default: op
