name: MiniGames
main: com.mcmiddleearth.minigames.MiniGamesPlugin
version: 1.1
description: MiniGames plugin
load: POSTWORLD
api-version: 1.13
softdepend: [Multiverse-Core]
depend: [PluginUtils]
commands:
    game:
        description: manage MiniGames plugin
        usage: TBA
    gc:
        description: MiniGames chat message
        usage: /gc <message> Sends a message to all participants of the MiniGame
permissions:
    minigames.*:
        description: Gives access to all miniGames commands
        default: op
    minigames.staff:
        description: Gives access to /game delete command
        default: op
    minigames.manager:
        description: Gives guides access to minigames commands for managing games
        default: op
    minigames.user:
        description: Gives access miniGames commands for players
        default: op
