name: MiniGames
main: com.mcmiddleearth.minigames.MiniGamesPlugin
version: 0.1
description: MiniGames plugin
commands:
    game:
        description: manage MiniGames plugin
        usage: TBA
    gc:
        description: MiniGames chat message
        usage: /gc <message> Sends a message to all participants of the MiniGame
permissions:
    minigames.*:
        description: Gives access to all miniGames commands
        default: op
        children:
            minigames.manager: true
            minigames.user: true
    minigames.manager:
        description: Gives guides access to miniGames commands for managing games
        default: op
    minigames.user:
        description: Gives access miniGames commands for players
        default: true
